### ISSUE TITLE
启动总是报MySql连接有问题

### ISSUE THREAD

**Issue by 188012887** [cxyxxx0924/renrenpay-server#1]
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
{ SequelizeAccessDeniedError: Access denied for user '18801'@'172.18.228.110' (using password: YES)
    at Utils.Promise.tap.then.catch.err (d:\renrenpay-server-master\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:141:19)
    at tryCatcher (d:\renrenpay-server-master\node_modules\bluebird\js\release\util.js:16:23)
 自己写了一个MySql连接有是好的，大神这个要怎么解决

--

**Comment by 188012887** [comment]
要设置环境变量 process.env.NODE_ENV === 'development' 吗？

**Comment by cxyxxx0924** [comment]
你吧你链接数据库的写法传上来看一下。

**Comment by 188012887** [comment]
const _ = require('lodash')

let config = {
    port: 3000,
    db: {
        host: process.env.host || '172.18.228.112',
        port: process.env.port || 3306,
        db:  process.env.db ||'db_renrenpay',
        dialect: 'mysql',
        user: process.env.username || 'root',
        password:  process.env.password || '123456_gcyh'
    },
    redis: {
        host: '127.0.0.1',
		port: 6379
    },
    websocket: {
        port: 7234
    },
    appid: process.env.appid || '15c821df1e52',
    adminPwd: process.env.adminpwd  || '123456',
    userid: '1',
    pay_userid: process.env.pay_userid ||'2088112172418889'
}

const init = () => {
    if (process.env.NODE_ENV === 'development') {
        const localConfig = {
            db: _.extend(config.db, {
                user: config.user,
                password: db.password
            })
        }
        config = _.extend(config, localConfig)
    }

    if (process.env.NODE_ENV === 'production') {
        const localConfig = {
            db: _.extend(config.db, {
                user: config.user,
                password: db.password
            })
        }
        config = _.extend(config, localConfig)
    }

    return config
}

module.exports = init()

**Comment by cxyxxx0924** [comment]
你数据库创建了吗

**Comment by 188012887** [comment]
数据库创建了,报的是SequelizeAccessDeniedError: Access denied for user '18801'@'172.18.228.110' (using password: YES) 连接数据库的用户名不应该是我配置的root吗,怎么会用我的电脑名称去连接？

**Comment by cxyxxx0924** [comment]
这个怀疑是电脑环境和账号权限问题，具体为什么数据库链接不上我也不清楚啊。你还是百度慢慢找的，我建议你用linux去部署服务器环境，别用windows
